refactor the update repository mech

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -14,4 +14,14 @@ jobs:
           fetch-depth: 0
 
       - name: Update repository?
-        run: ./bin/update-repository.sh
+        run: |
+          # configure user
+          git config user.name 'GitHub Actions'
+          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
+
+          # check for changes
+          ./bin/update-template.sh \
+            || { echo "failed to check for updates from template repo"; exit 1; }
+
+          # push changes
+          git push
